# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Machillka"
weight = 1

[social.params]
icon = "brand-github"

[[social]]
identifier = "bilibili"
name = "Bilibili"
url = "https://space.bilibili.com/611004244"
weight = 2

[social.params]
icon = "brand-bilibili"

[[social]]
identifier = "gmail"
name = "gmail"
url = "mailto:machillka2007@gmail.com"
weight = 3

[social.params]
icon = "brand-gmail"